<!-- This Code is generated by chatgpt  -->

<?php
error_reporting(0);
if (session_status() === PHP_SESSION_NONE) {
  session_start();
}
if(empty($_SESSION['dberror'])){
  header("location:home.php",true,302);
  exit();
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Connection Error</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <style>
    body {
      background-color: #f8f9fa;
    }
    .error-container {
      min-height: 100vh;
    }
    .error-icon {
      font-size: 4rem;
      color: #dc3545;
    }
    .error-message {
      font-size: 1.5rem;
      font-weight: 500;
    }
    .sub-message {
      font-size: 1rem;
      color: #6c757d;
    }
    .retry-btn {
      margin-top: 20px;
    }
  </style>
</head>
<body>

  <div class="container d-flex flex-column justify-content-center align-items-center error-container text-center">
    <div class="error-icon mb-4">
      <!-- You can replace this with a better icon if needed -->
      ⚠️
    </div>
    <div class="error-message text-danger mb-2">
      Could not connect to the server
    </div>
    <div class="sub-message mb-4">
      Please check your internet connection or try again later.
    </div>
    <a href="login.php">
    <button class="btn btn-danger retry-btn">Retry</button>
    </a>
  </div>

  <!-- Bootstrap JS (optional) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>
